appname="MndroLua"
appver="1.0.0"
appcode="10000"
appsdk="15"
path_pattern=""
packagename="com.androlua"
theme="Theme"
app_key=""
app_channel=""
developer=""
description=""
debugmode=true
user_permission={
  "INTERNET",
  "MANAGE_EXTERNAL_STORAGE",
  "WRITE_EXTERNAL_STORAGE"
}
