appname="插件"
appver="1.1"
packagename="com.androlua.plugin"
theme="Theme_Holo_Light"
developer="nirenr"
description="插件管理"
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
request_all_permissions_on_start=false
